development:
  adapter: postgresql
  database: bit_trade_db
  user: drewtunney
  host: localhost
  pool: 5
  timeout: 5000


production: 
  adapter: postgresql
  encoding: unicode
  database: bit_trade_db
  host: localhost
  pool: 5
  password: 
